### ISSUE TITLE
PropTypesのwarningを解消する

### ISSUE THREAD

**Issue by sin9270** [sin9270/task-chuter#33]
Active Tasksのページを開くと、PropTypesのwarningが出てしまう。titleContains、noteContains、lastLogの三つのpropsが必須になっているのにコンポーネントに渡っていないことが原因。これらのpropsは必須ではないので、propTypesの定義からisRequiredを削除する。

**Comment by dragogonone** [comment]
下記ファイルの `isRunning` でも同じ原因で warning 出るから、同じように isRequired を削除しよう
`client/src/containers/organisms/ActiveTask.js`

**Comment by dragogonone** [comment]
やる

**Comment by sin9270** [comment]
`isRunning`だけど、今は74行目の

```
<Div isRunning={props.task.status === TASK_STATUS.RUNNING}>
```

でpropsを渡していたつもりだったんだけど、propTypesのチェックはコンポーネント関数の引数に対して行われるみたいで、今の実装だと常に`isRunning`は`undefined`になってしまっていた。

なので、`isRunning`はpropTypes自体から消してしまって、styled-componentsの`border-color`の判定部分に、74行目の判定ロジックを移してしまいましょう。
